kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: eShoppe
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: transport