apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: eShoppe
  labels:
    app: filebeat
spec:  
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.5.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: podslogs
          mountPath: /var/log/pods
          readOnly: true
        - name: registry
          mountPath: /opt/filebeat/data
      volumes:
      # Bind previously defined ConfigMap
      - name: config
        configMap:
          defaultMode: 420
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: podslogs
        hostPath:
          path: /var/log/pods
      - name: registry
        emptyDir: {}