kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: eShoppe
spec:
  type: NodePort
  selector:
    app: logstash
  ports:  
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash