apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: eShoppe
  labels:
    app: pricing
spec:
  selector:
    app: pricing
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082