apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: eshoppe
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081